src/Entity/CarRegistration.php
<?php

namespace App\Entity;

use App\Repository\CarRegistrationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarRegistrationRepository::class)]
class CarRegistration
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $siret = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $bill_date = null;

    #[ORM\ManyToOne(inversedBy: 'CarRegistration')]
    private ?User $user = null;

    #[ORM\OneToOne(mappedBy: 'CarRegistration', cascade: ['persist', 'remove'])]
    private ?Garage $garage = null;

    #[ORM\OneToOne(mappedBy: 'CarRegistration', cascade: ['persist', 'remove'])]
    private ?Car $car = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): static
    {
        $this->siret = $siret;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getBillDate(): ?\DateTimeInterface
    {
        return $this->bill_date;
    }

    public function setBillDate(\DateTimeInterface $bill_date): static
    {
        $this->bill_date = $bill_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getGarage(): ?Garage
    {
        return $this->garage;
    }

    public function setGarage(?Garage $garage): static
    {
        // unset the owning side of the relation if necessary
        if ($garage === null && $this->garage !== null) {
            $this->garage->setCarRegistration(null);
        }

        // set the owning side of the relation if necessary
        if ($garage !== null && $garage->getCarRegistration() !== $this) {
            $garage->setCarRegistration($this);
        }

        $this->garage = $garage;

        return $this;
    }

    public function getCar(): ?Car
    {
        return $this->car;
    }

    public function setCar(?Car $car): static
    {
        // unset the owning side of the relation if necessary
        if ($car === null && $this->car !== null) {
            $this->car->setCarRegistration(null);
        }

        // set the owning side of the relation if necessary
        if ($car !== null && $car->getCarRegistration() !== $this) {
            $car->setCarRegistration($this);
        }

        $this->car = $car;

        return $this;
    }
}

src/Entity/Garage.php
<?php

namespace App\Entity;

use App\Repository\GarageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GarageRepository::class)]
class Garage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $phone_number = null;

    #[ORM\OneToOne(inversedBy: 'garage', cascade: ['persist', 'remove'])]
    private ?CarRegistration $CarRegistration = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(int $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getCarRegistration(): ?CarRegistration
    {
        return $this->CarRegistration;
    }

    public function setCarRegistration(?CarRegistration $CarRegistration): static
    {
        $this->CarRegistration = $CarRegistration;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\CarRegistrationRepository;
class DefaultController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(): Response
    {
        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
    }
    #[Route('/my_car_registration', name: 'app_my_car_registration')]
    public function myCarRegistration(CarRegistrationRepository $carRegistrationRepository): Response
    {
        $user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        $myCarRegistrations = $carRegistrationRepository->findBy(['user' => $user]);

        return $this->render('default/my_car_registration.html.twig', [
            'controller_name' => 'DefaultController',
            'myCarRegistrations' => $myCarRegistrations
        ]);
    }
}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}

	<div class="mt-24 flex flex-col items-center justify-center">
		<div class="flex flex-row-reverse items-center justify-center mb-24 ">
			
			<img class="h-56" src="{{ asset('img/papier.webp') }}" alt="Papier">
			<div class="baseline flex-col mr-20">
				<h1 class="text-4xl pb-5">Formulaire Voiture</h1>
				<p class="mb-5  w-96">Veuillez remplir le formulaire d'immatriculation de votre véhicule avec soin pour garantir une procédure fluide et rapide. Les informations fournies dans ce formulaire sont essentielles pour identifier et enregistrer votre voiture conformément aux réglementations locales.
				</p>

				<a href="{{ path('car_registration') }}" class="relative inline-flex items-center px-12 py-3 overflow-hidden text-lg font-medium text-blue-500 border-2 border-blue-500 rounded-full hover:text-white group hover:bg-gray-50">
					<span class="absolute left-0 block w-full h-0 transition-all bg-blue-500 opacity-100 group-hover:h-full top-1/2 group-hover:top-0 duration-400 ease"></span>
					<span class="absolute right-0 flex items-center justify-start w-10 h-10 duration-300 transform translate-x-full group-hover:translate-x-0 ease">
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path>
						</svg>
					</span>
					<span class="relative">Formulaire</span>
				</a>
			</div>
		</div>

		<div class="flex items-center justify-center pb-5">
			<img class="h-64" src="{{ asset('img/voiture.webp') }}" alt="Voiture">
			<div class="flex flex-col ml-20">
				<h1 class="text-4xl mb-10 ">ServiceAdministratif™</h1>
				<p class="w-96 baseline">
					Notre site web se distingue comme la meilleure option pour mettre à jour votre plaque d'immatriculation 
					sur un site administratif. Grâce à notre interface conviviale et intuitive, le processus de mise à jour 
					devient rapide et sans tracas. Nous comprenons l'importance de la conformité aux réglementations locales, 
					c'est pourquoi notre site est constamment mis à jour pour refléter les dernières exigences administratives. 
				</p>
			</div>
		</div>
	</div>
{% endblock %}

templates/default/my_car_registration.html.twig
{% extends 'base.html.twig' %}

{% block title %}Immat Voiture{% endblock %}

{% block body %}
    <div class="m-6">
        <h1 class="text-2xl font-bold mb-4">Mes Immatriculations</h1>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {% for carRegistration in myCarRegistrations %}
                <div class="bg-white p-6 shadow-md rounded-lg">
                    <p class="text-lg font-semibold">Nom: {{ carRegistration.firstname }}</p>
                    <p class="text-lg">Prénom: {{ carRegistration.name }}</p>
                    <p class="text-lg font-semibold">N° de siret: {{ carRegistration.siret }}</p>
                    <p class="text-lg">Date du dossier: {{ carRegistration.billDate|date('Y-m-d') }}</p>
                    <p class="text-lg font-semibold">Nom du garage: {{ carRegistration.garage.name }}</p>
                    <p class="text-lg">Adresse: {{ carRegistration.garage.address }}</p>
                    <p class="text-lg font-semibold">N° téléphone du garage: {{ carRegistration.garage.phoneNumber }}</p>
                    <p class="text-lg">Modèle de voiture: {{ carRegistration.car.model }}</p>
                    <p class="text-lg font-semibold">Couleur du véhicule: {{ carRegistration.car.color }}</p>
                    <p class="text-lg">Kilométrage du véhicule: {{ carRegistration.car.kilometer }}</p>
                    <p class="text-lg font-semibold">Prix du véhicule: {{ carRegistration.car.price }}€</p>
                    <p class="text-lg">Code d'immatriculation: {{ carRegistration.car.carRegistrationCode }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}